# Generated by Django 5.1.4 on 2024-12-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malihes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tarih', models.DateField()),
                ('Plaka', models.CharField(max_length=25)),
                ('Fisno', models.CharField(max_length=25)),
                ('Sofor', models.CharField(max_length=25)),
                ('Aciklama1', models.CharField(max_length=25)),
                ('Aciklama2', models.CharField(max_length=25)),
                ('Giris', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cikis', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['Tarih'],
            },
        ),
    ]
