# Generated by Django 5.1.4 on 2024-12-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malihes', '0003_sefer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kasa',
            options={'ordering': ['-Tarih']},
        ),
        migrations.AlterField(
            model_name='kasa',
            name='Aciklama1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='kasa',
            name='Aciklama2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='kasa',
            name='Fisno',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='kasa',
            name='Plaka',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='kasa',
            name='Sofor',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
