# Generated by Django 5.1.4 on 2024-12-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malihes', '0004_alter_kasa_options_alter_kasa_aciklama1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sefer',
            options={'ordering': ['Plakacekici']},
        ),
        migrations.RenameField(
            model_name='sefer',
            old_name='Plaka',
            new_name='Plakacekici',
        ),
        migrations.AddField(
            model_name='sefer',
            name='Plakadorse',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='sefer',
            name='Yol',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
