# Generated by Django 5.1.4 on 2024-12-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malihes', '0005_alter_sefer_options_rename_plaka_sefer_plakacekici_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Araclar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plaka', models.CharField(max_length=25)),
                ('Firma', models.CharField(blank=True, max_length=25, null=True)),
                ('Tür', models.CharField(blank=True, max_length=25, null=True)),
                ('Marka', models.CharField(blank=True, max_length=25, null=True)),
                ('Model', models.CharField(blank=True, max_length=25, null=True)),
                ('Sigbastarihi', models.DateField()),
                ('Sigbittarihi', models.DateField()),
                ('Sigtutari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Kasbastarihi', models.DateField()),
                ('Kasbittarihi', models.DateField()),
                ('Kastutari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Toplamtutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Ayliktutar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-Plaka'],
            },
        ),
    ]
