# Generated by Django 5.1.4 on 2025-01-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malihes', '0007_alter_araclar_kasbastarihi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='araclar',
            options={'ordering': ['Plaka']},
        ),
        migrations.AlterField(
            model_name='kasa',
            name='Aciklama1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kasa',
            name='Aciklama2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kasa',
            name='Sofor',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
