# Generated by Django 5.1.4 on 2025-01-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malihes', '0008_alter_araclar_options_alter_kasa_aciklama1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='araclar',
            options={'ordering': ['Firma', '-Tür', 'Plaka']},
        ),
        migrations.AlterModelOptions(
            name='kasa',
            options={'ordering': ['-Tarih', '-id']},
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Cikiskm',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Cikisyeri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Digergiderler',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Dovizkuru',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Istasyon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Kalan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Litre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Litrefiyati',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Musteri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Not',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Plakadorse',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Sofor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Toplamfiyat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Toplamyakit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Variskm',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Varistarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Varisyeri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Yol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sefer',
            name='Yuk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
