# Generated by Django 5.1.4 on 2025-01-19 16:40

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malihes', '0011_kur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adsoyad', models.CharField(max_length=100)),
                ('Bolum', models.CharField(blank=True, max_length=100, null=True)),
                ('Telefon', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('Maas', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['Adsoyad'],
            },
        ),
        migrations.AlterModelOptions(
            name='kur',
            options={'ordering': ['-tarih']},
        ),
    ]
